name: Commnader_Wars_AndroidTest
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.2.3'
  NDK_Version: r21e
  
jobs:
  install:
    name: Android Build
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            COMPILER_VERSION: 'android_armv7'
            qtPath: 'android_armv7'
            target: 'android'
            target-api-level: '27'
            abi : "armeabi-v7a"
        
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
          
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: ${{env.NDK_Version}}
        add-to-path: false
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
          
      
    - name: Configure CMake
      run:  |
        cmake \
        -S "${{github.workspace}}" \
        -B "${{github.workspace}}/build" \
        "-GNMake Makefiles JOM" \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        "-DQT_QMAKE_EXECUTABLE=${{github.workspace}}/qt/Qt/${{matrix.qtPath}}/${{matrix.COMPILER_VERSION}}/bin/qmake.bat" \        
        -DCMAKE_PREFIX_PATH="${{github.workspace}}/qt/Qt/${{matrix.qtPath}}/" \
        -DCMAKE_C_COMPILER='${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe' \
        -DCMAKE_CXX_COMPILER='${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe' \
        -DANDROID_NATIVE_API_LEVEL=${{ matrix.target-api }} \
        -DANDROID_NDK='${{ steps.setup-ndk.outputs.ndk-path }}' \
        -DCMAKE_TOOLCHAIN_FILE='${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake' \
        -DANDROID_ABI=${{ matrix.abi }} \
        -DANDROID_STL=c++_shared \        
        "-DCMAKE_FIND_ROOT_PATH=${{github.workspace}}/qt/Qt/${{matrix.qtPath}}/${{matrix.COMPILER_VERSION}}" \
        "-DQT_NO_GLOBAL_APK_TARGET_PART_OF_ALL:BOOL=ON" \
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install' \
        -DQt6_DIR='${{github.workspace}}/qt/Qt/${{matrix.qtPath}}/lib/cmake/Qt6/'

    - name: Build
      working-directory: '${{github.workspace}}/build'
      run: cmake --build '${{github.workspace}}/build' --config $BUILD_TYPE --target install -j16
